/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard.tickets'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardTicketsIndexRouteImport } from './routes/dashboard.tickets.index'
import { Route as DashboardTicketsTicketIdRouteImport } from './routes/dashboard.tickets.$ticketId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTicketsIndexRoute = DashboardTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTicketsRoute,
} as any)
const DashboardTicketsTicketIdRoute =
  DashboardTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => DashboardTicketsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/tickets': typeof DashboardTicketsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/tickets/$ticketId': typeof DashboardTicketsTicketIdRoute
  '/dashboard/tickets/': typeof DashboardTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/tickets/$ticketId': typeof DashboardTicketsTicketIdRoute
  '/dashboard/tickets': typeof DashboardTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/tickets': typeof DashboardTicketsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/tickets/$ticketId': typeof DashboardTicketsTicketIdRoute
  '/dashboard/tickets/': typeof DashboardTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/notifications'
    | '/dashboard/tickets'
    | '/dashboard/'
    | '/dashboard/tickets/$ticketId'
    | '/dashboard/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/notifications'
    | '/dashboard'
    | '/dashboard/tickets/$ticketId'
    | '/dashboard/tickets'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/notifications'
    | '/dashboard/tickets'
    | '/dashboard/'
    | '/dashboard/tickets/$ticketId'
    | '/dashboard/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tickets': {
      id: '/dashboard/tickets'
      path: '/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tickets/': {
      id: '/dashboard/tickets/'
      path: '/'
      fullPath: '/dashboard/tickets/'
      preLoaderRoute: typeof DashboardTicketsIndexRouteImport
      parentRoute: typeof DashboardTicketsRoute
    }
    '/dashboard/tickets/$ticketId': {
      id: '/dashboard/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/dashboard/tickets/$ticketId'
      preLoaderRoute: typeof DashboardTicketsTicketIdRouteImport
      parentRoute: typeof DashboardTicketsRoute
    }
  }
}

interface DashboardTicketsRouteChildren {
  DashboardTicketsTicketIdRoute: typeof DashboardTicketsTicketIdRoute
  DashboardTicketsIndexRoute: typeof DashboardTicketsIndexRoute
}

const DashboardTicketsRouteChildren: DashboardTicketsRouteChildren = {
  DashboardTicketsTicketIdRoute: DashboardTicketsTicketIdRoute,
  DashboardTicketsIndexRoute: DashboardTicketsIndexRoute,
}

const DashboardTicketsRouteWithChildren =
  DashboardTicketsRoute._addFileChildren(DashboardTicketsRouteChildren)

interface DashboardRouteChildren {
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardTicketsRoute: typeof DashboardTicketsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardTicketsRoute: DashboardTicketsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
